[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NEXT_PUBLIC_ENVIRONMENT = "production"
  NEXT_PUBLIC_ENABLE_API_LOGGING = "true"
  NEXT_PUBLIC_NETLIFY = "true"
  NEXT_PUBLIC_API_URL = "https://cryoprotect-8030e4025428.herokuapp.com/v1"
  NEXT_PUBLIC_RDKIT_API_URL = "https://cryoprotect-rdkit.fly.dev"
  NEXT_PUBLIC_CONVEX_URL = "https://upbeat-parrot-866.convex.cloud"
  NEXT_PUBLIC_USE_CONVEX = "true"
  # Other environment variables will be set through the Netlify UI or CLI

# Use the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# API health check endpoint
[[redirects]]
  from = "/api/health"
  to = "https://cryoprotect-8030e4025428.herokuapp.com/health"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# API CORS test endpoint
[[redirects]]
  from = "/api/test-cors"
  to = "https://cryoprotect-8030e4025428.herokuapp.com/test-cors"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# RDKit health check endpoint
[[redirects]]
  from = "/rdkit-api/health"
  to = "https://cryoprotect-rdkit.fly.dev/health"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# RDKit CORS test endpoint
[[redirects]]
  from = "/rdkit-api/test-cors"
  to = "https://cryoprotect-rdkit.fly.dev/test-cors"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Handle API redirects to Heroku backend
[[redirects]]
  from = "/api/*"
  to = "https://cryoprotect-8030e4025428.herokuapp.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Handle dynamic routes for experiments
[[redirects]]
  from = "/experiments/*"
  to = "/.netlify/functions/next/experiments/:splat"
  status = 200

# Handle dynamic routes for protocols
[[redirects]]
  from = "/protocols/*"
  to = "/.netlify/functions/next/protocols/:splat"
  status = 200

# These headers help secure your site
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.jsdelivr.net https://plausible.io https://*.netlify.app https://*.netlify.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.cryoprotect.app https://cryoprotect-8030e4025428.herokuapp.com https://cryoprotect-rdkit.fly.dev https://*.convex.cloud https://upbeat-parrot-866.convex.cloud https://*.supabase.co https://plausible.io https://*.netlify.app https://*.netlify.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# This redirects all requests to the Next.js app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200