[build]
  command = "chmod +x ./minimal-build.sh && ./minimal-build.sh"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"
  publish = ".next"
  
[build.environment]
  NEXT_PUBLIC_ENVIRONMENT = "production"
  NEXT_PUBLIC_ENABLE_API_LOGGING = "true"
  NEXT_PUBLIC_NETLIFY = "true"
  NEXT_PUBLIC_API_URL = "https://cryoprotect-8030e4025428.herokuapp.com/v1"
  # Other environment variables will be set through the Netlify UI or CLI

# API health connectivity endpoint
[[redirects]]
  from = "/api/v1/health/connectivity"
  to = "https://cryoprotect-8030e4025428.herokuapp.com/api/v1/health/connectivity"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Handle API redirects to Heroku backend
[[redirects]]
  from = "/api/*"
  to = "https://cryoprotect-8030e4025428.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# These headers help secure your site
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.jsdelivr.net https://plausible.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.cryoprotect.app https://*.supabase.co https://plausible.io;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# This ensures that React Router routes function correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Track 404s in Netlify Analytics
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404