# Netlify configuration file that overrides UI settings

[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  publish = "frontend/.next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://cryoprotect-8030e4025428.herokuapp.com/v1"
  NEXT_PUBLIC_USE_MOCK_DATA = "false"
  NEXT_PUBLIC_ENABLE_API_LOGGING = "true"
  NEXT_PUBLIC_ENVIRONMENT = "production"
  # Required for Next.js SSR
  NEXT_PRIVATE_TARGET = "server" 
  # Specify Node version
  NODE_VERSION = "20"

# Use Next.js Runtime v4
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/next-runtime"]

# Handle API redirects to Heroku backend
[[redirects]]
  from = "/api/*"
  to = "https://cryoprotect-8030e4025428.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# These headers help secure your site
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.cryoprotect.app https://*.supabase.co https://cryoprotect-8030e4025428.herokuapp.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# This ensures that React Router routes function correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200