[build]
  base = "minimal-frontend"
  publish = "out"
  command = "npm ci && npm run build"

# Disable git submodule functionality
[git]
  submodules = false
  
[build.environment]
  NEXT_PUBLIC_ENVIRONMENT = "production"
  NEXT_PUBLIC_ENABLE_API_LOGGING = "true"
  NEXT_PUBLIC_NETLIFY = "true"
  NEXT_PUBLIC_API_URL = "https://cryoprotect-8030e4025428.herokuapp.com/v1"
  NEXT_PUBLIC_RDKIT_API_URL = "https://cryoprotect-rdkit.fly.dev"
  NEXT_PUBLIC_CONVEX_URL = "https://upbeat-parrot-866.convex.cloud"
  NEXT_PUBLIC_USE_CONVEX = "false"
  # Other environment variables will be set through the Netlify UI or CLI

# API health check endpoint
[[redirects]]
  from = "/api/health"
  to = "https://cryoprotect-8030e4025428.herokuapp.com/health"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# API CORS test endpoint
[[redirects]]
  from = "/api/test-cors"
  to = "https://cryoprotect-8030e4025428.herokuapp.com/test-cors"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# RDKit health check endpoint
[[redirects]]
  from = "/rdkit-api/health"
  to = "https://cryoprotect-rdkit.fly.dev/health"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# RDKit CORS test endpoint
[[redirects]]
  from = "/rdkit-api/test-cors"
  to = "https://cryoprotect-rdkit.fly.dev/test-cors"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Handle API redirects to Heroku backend
[[redirects]]
  from = "/api/*"
  to = "https://cryoprotect-8030e4025428.herokuapp.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# These headers help secure your site
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.jsdelivr.net https://plausible.io https://*.netlify.app https://*.netlify.com https://identity.netlify.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.cryoprotect.app https://cryoprotect-8030e4025428.herokuapp.com https://cryoprotect-rdkit.fly.dev https://*.convex.cloud https://upbeat-parrot-866.convex.cloud https://*.supabase.co https://plausible.io https://*.netlify.app https://*.netlify.com https://identity.netlify.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Add specific redirects for routes with trailing slashes
[[redirects]]
  from = "/molecules"
  to = "/molecules/"
  status = 301
  force = true

[[redirects]]
  from = "/mixtures"
  to = "/mixtures/"
  status = 301
  force = true

[[redirects]]
  from = "/experiments"
  to = "/experiments/"
  status = 301
  force = true

[[redirects]]
  from = "/protocols"
  to = "/protocols/"
  status = 301
  force = true

[[redirects]]
  from = "/properties"
  to = "/properties/"
  status = 301
  force = true

# Dynamic route fallbacks for client-side routing
[[redirects]]
  from = "/experiments/*"
  to = "/experiments/"
  status = 200

[[redirects]]
  from = "/protocols/*"
  to = "/protocols/"
  status = 200

# This redirects all requests to the Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
