#!/bin/bash

# Test script for backend integration in CryoProtect
# This script helps test the integration after deploying changes

echo "==== CryoProtect Backend Integration Test Guide ===="
echo ""
echo "This script will guide you through testing the backend integration."
echo ""

echo "Step 1: Run the test CORS endpoints locally"
echo "--------------------------------------------"
echo "For the main API:"
echo "cd api && python test_cors.py"
echo ""
echo "For the RDKit service:"
echo "cd rdkit-service && python test_cors.py"
echo ""

echo "Step 2: Deploy updates to Netlify"
echo "--------------------------------"
echo "npm run build:with-convex"
echo "netlify deploy --prod"
echo ""

echo "Step 3: Test the connections"
echo "----------------------------"
echo "After deployment, run:"
echo "./test-connection.sh"
echo ""

echo "Step 4: Troubleshooting Common Issues"
echo "------------------------------------"
echo "1. If RDKit service is not responding:"
echo "   - Check if the service is running on fly.io"
echo "   - Verify the URL is correct in your environment variables"
echo ""
echo "2. If Convex integration fails:"
echo "   - Make sure you've run 'npm run convex:codegen'"
echo "   - Verify your Convex URL is correct"
echo "   - Check that your authentication is properly configured"
echo ""
echo "3. If CORS tests fail:"
echo "   - Ensure both backend services have the /test-cors endpoint"
echo "   - Verify CORS headers are properly configured"
echo "   - Check that the URLs in your redirects match exactly"
echo ""
echo "4. If Netlify redirects aren't working:"
echo "   - Verify the redirects in netlify.toml"
echo "   - Make sure your netlify.toml changes are deployed"
echo "   - Try clearing the Netlify cache: 'netlify plugins:install netlify-purge-cache-plugin && netlify purge-cache'"
echo ""

echo "Next Steps After Testing"
echo "----------------------"
echo "1. Once all tests pass, update the API on Heroku:"
echo "   - Deploy the cors_config.py file to Heroku"
echo "   - Add the /test-cors endpoint to your main API"
echo ""
echo "2. Update the RDKit service on fly.io:"
echo "   - Deploy the cors_config.py file to fly.io"
echo "   - Add the /test-cors endpoint to your RDKit service"
echo ""
echo "3. Verify the full integration in production"
echo "   - Visit the Convex test page after deployment"
echo "   - Test authentication and data operations"
echo ""

echo "For detailed instructions, refer to CORS_CONFIGURATION_GUIDE.md"
echo ""
echo "==== End of Test Guide ===="