/**
 * Generated Convex API
 * This file is automatically generated and should not be edited manually.
 */

export const api = {
  molecules: {
    query: {
      getMolecule: "molecules:query:getMolecule",
      getMoleculesByIds: "molecules:query:getMoleculesByIds",
      getRecentMolecules: "molecules:query:getRecentMolecules",
      searchMolecules: "molecules:query:searchMolecules"
    },
    mutations: {
      addMolecule: "molecules:mutations:addMolecule",
      deleteMolecule: "molecules:mutations:deleteMolecule",
      updateMolecule: "molecules:mutations:updateMolecule"
    }
  },
  mixtures: {
    mixtures: {
      getMixture: "mixtures:mixtures:getMixture",
      getMixturesByIds: "mixtures:mixtures:getMixturesByIds",
      getRecentMixtures: "mixtures:mixtures:getRecentMixtures",
      searchMixtures: "mixtures:mixtures:searchMixtures"
    },
    mutations: {
      addMixture: "mixtures:mutations:addMixture",
      deleteMixture: "mixtures:mutations:deleteMixture",
      updateMixture: "mixtures:mutations:updateMixture"
    }
  },
  experiments: {
    experiments: {
      getExperiment: "experiments:experiments:getExperiment",
      getExperimentsByIds: "experiments:experiments:getExperimentsByIds",
      getRecentExperiments: "experiments:experiments:getRecentExperiments",
      searchExperiments: "experiments:experiments:searchExperiments"
    },
    protocols: {
      getProtocol: "experiments:protocols:getProtocol",
      getProtocolsByIds: "experiments:protocols:getProtocolsByIds",
      getRecentProtocols: "experiments:protocols:getRecentProtocols",
      searchProtocols: "experiments:protocols:searchProtocols"
    }
  }
};