[build]
  publish = "out"
  command = "npm run build"
  
# Disable git submodule functionality
[git]
  submodules = false
  
[build.environment]
  NEXT_PUBLIC_ENVIRONMENT = "production"
  NEXT_PUBLIC_NETLIFY = "true"
  NEXT_PUBLIC_USE_CONVEX = "false"
  NEXT_PUBLIC_API_URL = "https://cryoprotect-8030e4025428.herokuapp.com/api"
  NEXT_PUBLIC_RDKIT_API_URL = "https://cryoprotect-rdkit.fly.dev"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "https://cryoprotect-8030e4025428.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/rdkit-api/*"
  to = "https://cryoprotect-rdkit.fly.dev/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# This redirect rule handles client-side routing for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# These headers help secure your site
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' https://cryoprotect-8030e4025428.herokuapp.com https://cryoprotect-rdkit.fly.dev https://*.netlify.app https://*.netlify.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"