name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - master
      - heroku-full-app  # Add your current branch for testing
      - netlify-autodeploy  # New branch for automatic Netlify deployments
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NEXT_PUBLIC_API_URL: https://cryoprotect-8030e4025428.herokuapp.com/v1
      NEXT_PUBLIC_USE_MOCK_DATA: false
      NEXT_PUBLIC_ENABLE_API_LOGGING: true
      NEXT_PUBLIC_ENVIRONMENT: production
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      PROTECTION_BYPASS: ${{ secrets.PROTECTION_BYPASS }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm run install-deps
      
      - name: Update API endpoints
        working-directory: ./frontend
        run: npm run update-api-endpoints
      
      - name: Fix vulnerabilities
        working-directory: ./frontend
        run: |
          if [ -f ./fix-vulnerabilities.sh ]; then
            chmod +x ./fix-vulnerabilities.sh
            ./fix-vulnerabilities.sh
          else
            npm audit fix --force
          fi

      - name: Configure for Pages Router
        working-directory: ./frontend
        run: |
          if [ -f ./use-pages-router.sh ]; then
            chmod +x ./use-pages-router.sh
            ./use-pages-router.sh
          fi

      - name: Configure next.config.js for static export
        working-directory: ./frontend
        run: |
          cat > next.config.js << EOL
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            reactStrictMode: true,
            swcMinify: true,
            images: {
              unoptimized: true,
            },
            eslint: {
              ignoreDuringBuilds: true
            },
            typescript: {
              ignoreBuildErrors: true
            },
            
            // React 18 specific settings
            compiler: {
              styledComponents: true
            },
            
            // Static export configuration for Pages Router
            output: 'export',
            trailingSlash: true,
            distDir: 'out'
          };
          
          module.exports = nextConfig;
          EOL

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
      
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      - name: Create Netlify redirects
        working-directory: ./frontend
        run: |
          cat > out/_redirects << EOL
          # API routes should redirect to the backend
          /api/*  ${NEXT_PUBLIC_API_URL}/:splat  200
          
          # Handle dynamic routes 
          /molecules/*  /molecules/index.html  200
          /mixtures/*  /mixtures/index.html  200
          /experiments/*  /experiments/index.html  200
          /protocols/*  /protocols/index.html  200
          
          # SPA fallback for all other routes
          /*  /index.html  200
          EOL

      - name: Deploy to Netlify (Pull Request)
        if: github.event_name == 'pull_request'
        working-directory: ./frontend
        run: |
          export FRONTEND_URL="https://$(netlify deploy --json --dir=out | jq -r '.deploy_url' | sed 's/https:\/\///')"
          netlify deploy --dir=out --json > deploy_output.json
          echo "NETLIFY_PREVIEW_URL=$(jq -r '.deploy_url' deploy_output.json)" >> $GITHUB_ENV
        
      - name: Add PR Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = process.env.NETLIFY_PREVIEW_URL;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Netlify preview deployed to: [${url}](${url})`
            });
      
      - name: Deploy to Netlify (Production)
        if: github.event_name == 'push'
        working-directory: ./frontend
        run: |
          export FRONTEND_URL="https://$(netlify deploy --json --prod --dir=out | jq -r '.url' | sed 's/https:\/\///')"
          netlify deploy --prod --dir=out
      
      - name: Restore App Router
        working-directory: ./frontend
        run: |
          if [ -f ./restore-app-router.sh ]; then
            chmod +x ./restore-app-router.sh
            ./restore-app-router.sh
          fi

      - name: Update Heroku with Netlify URL
        if: github.event_name == 'push' && secrets.HEROKU_API_KEY != ''
        run: |
          NETLIFY_URL=$(netlify sites:current --json | jq -r '.ssl_url')
          curl -X PATCH \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3" \
            -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
            -d "{\"config\": {\"NETLIFY_FRONTEND_URL\": \"$NETLIFY_URL\"}}" \
            "https://api.heroku.com/apps/cryoprotect/config-vars"